"""add sales: import_batches + raw_sales

Revision ID: 00f1b8058e5e
Revises: 1aa09ead4137
Create Date: 2026-04-19 19:45:45.282672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '00f1b8058e5e'
down_revision: Union[str, None] = '1aa09ead4137'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_batches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by_user_id', sa.UUID(), nullable=True),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('inserted_rows', sa.Integer(), nullable=False),
    sa.Column('skipped_rows', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_batches_tenant_id'), 'import_batches', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_import_batches_uploaded_by_user_id'), 'import_batches', ['uploaded_by_user_id'], unique=False)
    op.create_table('raw_sales',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('client', sa.String(length=255), nullable=False),
    sa.Column('channel', sa.String(length=100), nullable=True),
    sa.Column('product_code', sa.String(length=100), nullable=True),
    sa.Column('product_name', sa.String(length=500), nullable=True),
    sa.Column('category_code', sa.String(length=100), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_sales_agent'), 'raw_sales', ['agent'], unique=False)
    op.create_index(op.f('ix_raw_sales_batch_id'), 'raw_sales', ['batch_id'], unique=False)
    op.create_index(op.f('ix_raw_sales_client'), 'raw_sales', ['client'], unique=False)
    op.create_index(op.f('ix_raw_sales_month'), 'raw_sales', ['month'], unique=False)
    op.create_index(op.f('ix_raw_sales_product_code'), 'raw_sales', ['product_code'], unique=False)
    op.create_index(op.f('ix_raw_sales_tenant_id'), 'raw_sales', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_raw_sales_year'), 'raw_sales', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raw_sales_year'), table_name='raw_sales')
    op.drop_index(op.f('ix_raw_sales_tenant_id'), table_name='raw_sales')
    op.drop_index(op.f('ix_raw_sales_product_code'), table_name='raw_sales')
    op.drop_index(op.f('ix_raw_sales_month'), table_name='raw_sales')
    op.drop_index(op.f('ix_raw_sales_client'), table_name='raw_sales')
    op.drop_index(op.f('ix_raw_sales_batch_id'), table_name='raw_sales')
    op.drop_index(op.f('ix_raw_sales_agent'), table_name='raw_sales')
    op.drop_table('raw_sales')
    op.drop_index(op.f('ix_import_batches_uploaded_by_user_id'), table_name='import_batches')
    op.drop_index(op.f('ix_import_batches_tenant_id'), table_name='import_batches')
    op.drop_table('import_batches')
    # ### end Alembic commands ###
