"""add user totp fields

Revision ID: 08b40d81434e
Revises: 56b6f294d242
Create Date: 2026-04-19 22:24:42.773563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '08b40d81434e'
down_revision: Union[str, None] = '56b6f294d242'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('totp_secret', sa.String(length=32), nullable=True))
    op.add_column('users', sa.Column('totp_enabled', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'totp_enabled')
    op.drop_column('users', 'totp_secret')
    # ### end Alembic commands ###
