"""add gallery: folders + photos

Revision ID: 091e2d2237ea
Revises: a002d3ae2e28
Create Date: 2026-04-19 21:53:51.363649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '091e2d2237ea'
down_revision: Union[str, None] = 'a002d3ae2e28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gallery_folders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'type', 'name', name='uq_gallery_folders_tenant_type_name')
    )
    op.create_index(op.f('ix_gallery_folders_tenant_id'), 'gallery_folders', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_gallery_folders_type'), 'gallery_folders', ['type'], unique=False)
    op.create_table('gallery_photos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('folder_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('object_key', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('caption', sa.String(length=500), nullable=True),
    sa.Column('uploaded_by_user_id', sa.UUID(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['folder_id'], ['gallery_folders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('object_key')
    )
    op.create_index(op.f('ix_gallery_photos_folder_id'), 'gallery_photos', ['folder_id'], unique=False)
    op.create_index(op.f('ix_gallery_photos_tenant_id'), 'gallery_photos', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gallery_photos_tenant_id'), table_name='gallery_photos')
    op.drop_index(op.f('ix_gallery_photos_folder_id'), table_name='gallery_photos')
    op.drop_table('gallery_photos')
    op.drop_index(op.f('ix_gallery_folders_type'), table_name='gallery_folders')
    op.drop_index(op.f('ix_gallery_folders_tenant_id'), table_name='gallery_folders')
    op.drop_table('gallery_folders')
    # ### end Alembic commands ###
