"""add stores: stores + store_aliases + raw_sales.store_id

Revision ID: 095bd8be47d3
Revises: 00f1b8058e5e
Create Date: 2026-04-19 19:52:28.425179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '095bd8be47d3'
down_revision: Union[str, None] = '00f1b8058e5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('chain', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_stores_tenant_name')
    )
    op.create_index(op.f('ix_stores_chain'), 'stores', ['chain'], unique=False)
    op.create_index(op.f('ix_stores_tenant_id'), 'stores', ['tenant_id'], unique=False)
    op.create_table('store_aliases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('raw_client', sa.String(length=255), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('resolved_by_user_id', sa.UUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resolved_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'raw_client', name='uq_store_aliases_tenant_rawclient')
    )
    op.create_index(op.f('ix_store_aliases_raw_client'), 'store_aliases', ['raw_client'], unique=False)
    op.create_index(op.f('ix_store_aliases_store_id'), 'store_aliases', ['store_id'], unique=False)
    op.create_index(op.f('ix_store_aliases_tenant_id'), 'store_aliases', ['tenant_id'], unique=False)
    op.add_column('raw_sales', sa.Column('store_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_raw_sales_store_id'), 'raw_sales', ['store_id'], unique=False)
    op.create_foreign_key(None, 'raw_sales', 'stores', ['store_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'raw_sales', type_='foreignkey')
    op.drop_index(op.f('ix_raw_sales_store_id'), table_name='raw_sales')
    op.drop_column('raw_sales', 'store_id')
    op.drop_index(op.f('ix_store_aliases_tenant_id'), table_name='store_aliases')
    op.drop_index(op.f('ix_store_aliases_store_id'), table_name='store_aliases')
    op.drop_index(op.f('ix_store_aliases_raw_client'), table_name='store_aliases')
    op.drop_table('store_aliases')
    op.drop_index(op.f('ix_stores_tenant_id'), table_name='stores')
    op.drop_index(op.f('ix_stores_chain'), table_name='stores')
    op.drop_table('stores')
    # ### end Alembic commands ###
