"""add agent_store_assignments

Revision ID: 56b6f294d242
Revises: 8a3dc5daa35d
Create Date: 2026-04-19 22:14:59.003517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '56b6f294d242'
down_revision: Union[str, None] = '8a3dc5daa35d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_store_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'agent_id', 'store_id', name='uq_ag_st_tenant_ag_st')
    )
    op.create_index(op.f('ix_agent_store_assignments_agent_id'), 'agent_store_assignments', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_store_assignments_store_id'), 'agent_store_assignments', ['store_id'], unique=False)
    op.create_index(op.f('ix_agent_store_assignments_tenant_id'), 'agent_store_assignments', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_store_assignments_tenant_id'), table_name='agent_store_assignments')
    op.drop_index(op.f('ix_agent_store_assignments_store_id'), table_name='agent_store_assignments')
    op.drop_index(op.f('ix_agent_store_assignments_agent_id'), table_name='agent_store_assignments')
    op.drop_table('agent_store_assignments')
    # ### end Alembic commands ###
