"""add_marketing_tables

Revision ID: 722a52111e84
Revises: ccabf9544074
Create Date: 2026-04-20 16:29:25.902811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '722a52111e84'
down_revision: Union[str, None] = 'ccabf9544074'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facing_brands',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('is_own', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_facing_brands_tenant_name')
    )
    op.create_index(op.f('ix_facing_brands_tenant_id'), 'facing_brands', ['tenant_id'], unique=False)
    op.create_table('facing_raioane',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['facing_raioane.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_facing_raioane_tenant_name')
    )
    op.create_index(op.f('ix_facing_raioane_parent_id'), 'facing_raioane', ['parent_id'], unique=False)
    op.create_index(op.f('ix_facing_raioane_tenant_id'), 'facing_raioane', ['tenant_id'], unique=False)
    op.create_table('facing_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('raion_id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('facings_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['facing_brands.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['raion_id'], ['facing_raioane.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'year', 'month', 'store_id', 'raion_id', 'brand_id', name='uq_facing_snap_tenant_ym_store_raion_brand')
    )
    op.create_index(op.f('ix_facing_snapshots_brand_id'), 'facing_snapshots', ['brand_id'], unique=False)
    op.create_index(op.f('ix_facing_snapshots_month'), 'facing_snapshots', ['month'], unique=False)
    op.create_index(op.f('ix_facing_snapshots_raion_id'), 'facing_snapshots', ['raion_id'], unique=False)
    op.create_index(op.f('ix_facing_snapshots_store_id'), 'facing_snapshots', ['store_id'], unique=False)
    op.create_index(op.f('ix_facing_snapshots_tenant_id'), 'facing_snapshots', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_facing_snapshots_year'), 'facing_snapshots', ['year'], unique=False)
    op.create_table('panou_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('location', sa.String(length=300), nullable=True),
    sa.Column('installed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_panou_items_kind'), 'panou_items', ['kind'], unique=False)
    op.create_index(op.f('ix_panou_items_store_id'), 'panou_items', ['store_id'], unique=False)
    op.create_index(op.f('ix_panou_items_tenant_id'), 'panou_items', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_panou_items_tenant_id'), table_name='panou_items')
    op.drop_index(op.f('ix_panou_items_store_id'), table_name='panou_items')
    op.drop_index(op.f('ix_panou_items_kind'), table_name='panou_items')
    op.drop_table('panou_items')
    op.drop_index(op.f('ix_facing_snapshots_year'), table_name='facing_snapshots')
    op.drop_index(op.f('ix_facing_snapshots_tenant_id'), table_name='facing_snapshots')
    op.drop_index(op.f('ix_facing_snapshots_store_id'), table_name='facing_snapshots')
    op.drop_index(op.f('ix_facing_snapshots_raion_id'), table_name='facing_snapshots')
    op.drop_index(op.f('ix_facing_snapshots_month'), table_name='facing_snapshots')
    op.drop_index(op.f('ix_facing_snapshots_brand_id'), table_name='facing_snapshots')
    op.drop_table('facing_snapshots')
    op.drop_index(op.f('ix_facing_raioane_tenant_id'), table_name='facing_raioane')
    op.drop_index(op.f('ix_facing_raioane_parent_id'), table_name='facing_raioane')
    op.drop_table('facing_raioane')
    op.drop_index(op.f('ix_facing_brands_tenant_id'), table_name='facing_brands')
    op.drop_table('facing_brands')
    # ### end Alembic commands ###
