"""add products: products + product_aliases + raw_sales.product_id

Revision ID: 725be26669d9
Revises: ce7b93c275de
Create Date: 2026-04-19 20:16:47.313546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '725be26669d9'
down_revision: Union[str, None] = 'ce7b93c275de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_products_tenant_code')
    )
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_index(op.f('ix_products_tenant_id'), 'products', ['tenant_id'], unique=False)
    op.create_table('product_aliases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('raw_code', sa.String(length=100), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('resolved_by_user_id', sa.UUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'raw_code', name='uq_product_aliases_tenant_rawcode')
    )
    op.create_index(op.f('ix_product_aliases_product_id'), 'product_aliases', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_aliases_raw_code'), 'product_aliases', ['raw_code'], unique=False)
    op.create_index(op.f('ix_product_aliases_tenant_id'), 'product_aliases', ['tenant_id'], unique=False)
    op.add_column('raw_sales', sa.Column('product_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_raw_sales_product_id'), 'raw_sales', ['product_id'], unique=False)
    op.create_foreign_key(None, 'raw_sales', 'products', ['product_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'raw_sales', type_='foreignkey')
    op.drop_index(op.f('ix_raw_sales_product_id'), table_name='raw_sales')
    op.drop_column('raw_sales', 'product_id')
    op.drop_index(op.f('ix_product_aliases_tenant_id'), table_name='product_aliases')
    op.drop_index(op.f('ix_product_aliases_raw_code'), table_name='product_aliases')
    op.drop_index(op.f('ix_product_aliases_product_id'), table_name='product_aliases')
    op.drop_table('product_aliases')
    op.drop_index(op.f('ix_products_tenant_id'), table_name='products')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
