"""add user lockout fields

Revision ID: aaf7f45b40e9
Revises: bc06488a07fb
Create Date: 2026-04-19 20:45:27.947799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'aaf7f45b40e9'
down_revision: Union[str, None] = 'bc06488a07fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('failed_login_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'locked_until')
    op.drop_column('users', 'failed_login_count')
    # ### end Alembic commands ###
