"""add agents: agents + agent_aliases + raw_sales.agent_id

Revision ID: ce7b93c275de
Revises: 095bd8be47d3
Create Date: 2026-04-19 19:57:03.368806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ce7b93c275de'
down_revision: Union[str, None] = '095bd8be47d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'full_name', name='uq_agents_tenant_fullname')
    )
    op.create_index(op.f('ix_agents_tenant_id'), 'agents', ['tenant_id'], unique=False)
    op.create_table('agent_aliases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('raw_agent', sa.String(length=255), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('resolved_by_user_id', sa.UUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'raw_agent', name='uq_agent_aliases_tenant_rawagent')
    )
    op.create_index(op.f('ix_agent_aliases_agent_id'), 'agent_aliases', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_aliases_raw_agent'), 'agent_aliases', ['raw_agent'], unique=False)
    op.create_index(op.f('ix_agent_aliases_tenant_id'), 'agent_aliases', ['tenant_id'], unique=False)
    op.add_column('raw_sales', sa.Column('agent_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_raw_sales_agent_id'), 'raw_sales', ['agent_id'], unique=False)
    op.create_foreign_key(None, 'raw_sales', 'agents', ['agent_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'raw_sales', type_='foreignkey')
    op.drop_index(op.f('ix_raw_sales_agent_id'), table_name='raw_sales')
    op.drop_column('raw_sales', 'agent_id')
    op.drop_index(op.f('ix_agent_aliases_tenant_id'), table_name='agent_aliases')
    op.drop_index(op.f('ix_agent_aliases_raw_agent'), table_name='agent_aliases')
    op.drop_index(op.f('ix_agent_aliases_agent_id'), table_name='agent_aliases')
    op.drop_table('agent_aliases')
    op.drop_index(op.f('ix_agents_tenant_id'), table_name='agents')
    op.drop_table('agents')
    # ### end Alembic commands ###
