"""add product_categories brands product.category_id brand_id

Revision ID: ec0ec9055e85
Revises: 4eeab1e49ef2
Create Date: 2026-04-20 11:22:41.853259

"""
from typing import Sequence, Union
from uuid import uuid4

from alembic import op
import sqlalchemy as sa


revision: str = 'ec0ec9055e85'
down_revision: Union[str, None] = '4eeab1e49ef2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    # Seed catalog global — codurile sunt standardizate la nivel SaaS.
    product_categories_table = sa.table(
        'product_categories',
        sa.column('id', sa.UUID()),
        sa.column('code', sa.String()),
        sa.column('label', sa.String()),
        sa.column('sort_order', sa.Integer()),
    )
    op.bulk_insert(product_categories_table, [
        {'id': uuid4(), 'code': 'EPS', 'label': 'Polistiren Expandat', 'sort_order': 10},
        {'id': uuid4(), 'code': 'MU', 'label': 'Mortare Uscate', 'sort_order': 20},
        {'id': uuid4(), 'code': 'UMEDE', 'label': 'Umede', 'sort_order': 30},
        {'id': uuid4(), 'code': 'VARSACI', 'label': 'Vărsaci (Vrac)', 'sort_order': 40},
    ])
    op.create_table('brands',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_private_label', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_brands_tenant_name')
    )
    op.create_index(op.f('ix_brands_tenant_id'), 'brands', ['tenant_id'], unique=False)
    op.create_table('brand_aliases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('raw_value', sa.String(length=200), nullable=False),
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('resolved_by_user_id', sa.UUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'raw_value', name='uq_brand_aliases_tenant_rawvalue')
    )
    op.create_index(op.f('ix_brand_aliases_brand_id'), 'brand_aliases', ['brand_id'], unique=False)
    op.create_index(op.f('ix_brand_aliases_raw_value'), 'brand_aliases', ['raw_value'], unique=False)
    op.create_index(op.f('ix_brand_aliases_tenant_id'), 'brand_aliases', ['tenant_id'], unique=False)
    op.create_table('product_category_aliases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('raw_value', sa.String(length=100), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('resolved_by_user_id', sa.UUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['product_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'raw_value', name='uq_product_category_aliases_tenant_rawvalue')
    )
    op.create_index(op.f('ix_product_category_aliases_category_id'), 'product_category_aliases', ['category_id'], unique=False)
    op.create_index(op.f('ix_product_category_aliases_raw_value'), 'product_category_aliases', ['raw_value'], unique=False)
    op.create_index(op.f('ix_product_category_aliases_tenant_id'), 'product_category_aliases', ['tenant_id'], unique=False)
    op.add_column('products', sa.Column('category_id', sa.UUID(), nullable=True))
    op.add_column('products', sa.Column('brand_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_products_brand_id'), 'products', ['brand_id'], unique=False)
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
    op.create_foreign_key(None, 'products', 'product_categories', ['category_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'products', 'brands', ['brand_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_index(op.f('ix_products_category_id'), table_name='products')
    op.drop_index(op.f('ix_products_brand_id'), table_name='products')
    op.drop_column('products', 'brand_id')
    op.drop_column('products', 'category_id')
    op.drop_index(op.f('ix_product_category_aliases_tenant_id'), table_name='product_category_aliases')
    op.drop_index(op.f('ix_product_category_aliases_raw_value'), table_name='product_category_aliases')
    op.drop_index(op.f('ix_product_category_aliases_category_id'), table_name='product_category_aliases')
    op.drop_table('product_category_aliases')
    op.drop_index(op.f('ix_brand_aliases_tenant_id'), table_name='brand_aliases')
    op.drop_index(op.f('ix_brand_aliases_raw_value'), table_name='brand_aliases')
    op.drop_index(op.f('ix_brand_aliases_brand_id'), table_name='brand_aliases')
    op.drop_table('brand_aliases')
    op.drop_index(op.f('ix_brands_tenant_id'), table_name='brands')
    op.drop_table('brands')
    op.drop_table('product_categories')
    # ### end Alembic commands ###
